services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blitzapp-db
          property: connectionString
