services:
  - type: web
    name: briankarina
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
